# dist: focal

language: php

services: 
  - mysql

php:
 - '7.3'
 - '7.4'
 - '8.0'
# - '8.1'


# blocklist
branches:
  except:
  - demo
  - dev
  - master

# safelist
branches:
  only:
  - test

before_script:
  - composer self-update
  - composer install --no-interaction --ignore-platform-reqs

before_install: 
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `avi-lib-test`;'
  - mysql < ./tests/assets/test.sql

script:
  - ./vendor/bin/phpunit