
language: php
dist: focal
php:
  - '8.1'
  - '8.0'
  - '7.4'
  - '7.3'



# blocklist
branches:
  except:
  - demo
  - dev
  - master

# safelist
branches:
  only:
  - test

before_script:
  - composer self-update
  - composer install --no-interaction --ignore-platform-reqs

script:
  - ./vendor/bin/phpunit