language: php
dist: bionic

php:
  - 7.4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  # Deactivate xdebug
  - phpenv config-rm xdebug.ini
  - composer install --ignore-platform-reqs

script:
  - ./vendor/bin/phpunit

jobs:
  include:

    - stage: Code style
      php: 7.4
      script:
        - ./vendor/bin/php-cs-fixer fix --diff --verbose --dry-run

    - stage: API documentations
      if: tag is present AND branch = master
      php: 7.4
      before_script:
        - curl -LO https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.0.0-rc/phpDocumentor.phar
      script:
        - php phpDocumentor.phar --directory src/ --target docs/api
      deploy:
        provider: pages
        skip-cleanup: true
        local-dir: docs/api
        github-token: $GITHUB_TOKEN
