name: CI

on:
  push:
    branches: [ test ]

permissions:
  contents: read

jobs:

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
